
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce

    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  goapp:
    build: .
    container_name: ecommerce
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      DB_USER: root
      DB_PASSWORD:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ecommerce

volumes:
  mysql_data:
